import { AgentForgeError, CancellationError, createRunId, type Agent, type EventBus, type ModelProvider, type ToolLike } from '@agentforge-oss/core';
import type { WorkflowContext, WorkflowNode, WorkflowState } from './types.js';

export function inputNode(id: string, transform: (input: unknown) => unknown = (input) => input): WorkflowNode { return { id, type: 'input', async run(state) { return transform(state.input); } }; }
export function agentNode(options: { id: string; agent: Agent; input?: (state: WorkflowState) => string; retries?: number }): WorkflowNode { return { id: options.id, type: 'agent', retries: options.retries, async run(state) { const prompt = options.input?.(state) ?? String(state.value ?? state.input ?? ''); return (await options.agent.run(prompt, { signal: state.signal, metadata: { workflowRunId: state.runId } })).output; } }; }
export function modelNode(options: { id: string; model: ModelProvider; input?: (state: WorkflowState) => import('@agentforge-oss/core').Message[]; retries?: number }): WorkflowNode { return { id: options.id, type: 'model', retries: options.retries, async run(state) { const messages = options.input?.(state) ?? [{ role: 'user', content: String(state.value ?? state.input ?? '') }]; return (await options.model.generate({ messages, signal: state.signal })).content; } }; }
export function toolNode(options: { id: string; tool: ToolLike; input?: (state: WorkflowState) => unknown; retries?: number }): WorkflowNode { return { id: options.id, type: 'tool', retries: options.retries, async run(state) { return options.tool.execute(options.input?.(state) ?? state.value, { runId: state.runId, signal: state.signal }); } }; }
export function transformNode<T = unknown, R = unknown>(id: string, transform: (value: T, state: WorkflowState<T>) => R, retries = 0): WorkflowNode<R> { return { id, type: 'transform', retries, async run(state) { return transform(state.value as T, state as WorkflowState<T>); } }; }
export function conditionNode(id: string, predicate: (value: unknown, state: WorkflowState) => boolean): WorkflowNode<boolean> { return { id, type: 'condition', async run(state) { return predicate(state.value, state); } }; }
export function approvalNode(id: string, approve: (value: unknown, state: WorkflowState) => boolean | Promise<boolean>): WorkflowNode<boolean> { return { id, type: 'approval', async run(state) { return approve(state.value, state); } }; }
export function outputNode(id: string, select: (state: WorkflowState) => unknown = (state) => state.value): WorkflowNode { return { id, type: 'output', async run(state) { return select(state); } }; }
export function parallelNode(id: string, branches: Array<(state: WorkflowState, context: WorkflowContext) => unknown | Promise<unknown>>, retries = 0): WorkflowNode<unknown[]> { return { id, type: 'parallel', retries, async run(state, context) { return Promise.all(branches.map((branch) => branch(state, context))); } }; }
export function customNode<T = unknown>(id: string, run: (state: WorkflowState, context: WorkflowContext) => T | Promise<T>, retries = 0): WorkflowNode<T> { return { id, type: 'custom', retries, run }; }

export function connect(from: string, to: string, options: { label?: string; condition?: (value: unknown, state: WorkflowState) => boolean } = {}) { return { from, to, ...options }; }
export const branch = (label: string) => ({ label });
