import { EventBus, AgentForgeError, CancellationError, createRunId } from '@agentforge-oss/core';
import type { WorkflowDefinition, WorkflowEdge, WorkflowNode, WorkflowResult, WorkflowRunOptions, WorkflowState, WorkflowStep } from './types.js';

export class Workflow {
  readonly name: string; readonly nodes: ReadonlyMap<string, WorkflowNode>; readonly edges: readonly WorkflowEdge[]; readonly events: EventBus; readonly metadata?: Record<string, unknown>; readonly startId?: string; readonly maxSteps: number;
  constructor(definition: WorkflowDefinition & { events?: EventBus }) { this.name = definition.name; this.nodes = new Map(definition.nodes.map((node) => [node.id, node])); this.edges = definition.edges; this.events = definition.events ?? new EventBus(); this.metadata = definition.metadata; this.startId = definition.start; this.maxSteps = definition.maxSteps ?? 100; if (!this.nodes.size) throw new Error('Workflow requires at least one node'); if (this.startId && !this.nodes.has(this.startId)) throw new Error(`Workflow start node not found: ${this.startId}`); for (const edge of this.edges) { if (!this.nodes.has(edge.from) || !this.nodes.has(edge.to)) throw new Error(`Invalid workflow edge ${edge.from} -> ${edge.to}`); } }
  async run(input: unknown, options: WorkflowRunOptions = {}): Promise<WorkflowResult> {
    const runId = createRunId('workflow'); const started = Date.now(); const signal = options.signal ?? new AbortController().signal; const state: WorkflowState = { input, value: input, data: {}, history: [], runId, signal }; const maxSteps = options.maxSteps ?? this.maxSteps;
    await this.emit('workflow.started', runId, { workflow: this.name, input });
    try { let current: WorkflowNode | undefined = this.startNode(); let count = 0; while (current) { const node = current; if (signal.aborted) throw new CancellationError(); if (++count > maxSteps) throw new AgentForgeError(`Workflow exceeded maximum steps (${maxSteps})`, 'MAX_STEPS'); const step = await this.executeNode(node, state, runId, options); state.history.push(step); state.value = step.output; state.data[node.id] = step.output; const edges = this.edges.filter((edge) => edge.from === node.id && (!edge.condition || edge.condition(step.output, state))); const selected = this.selectEdge(edges, step.output); current = selected ? this.nodes.get(selected.to) : undefined; }
      const result = { runId, output: state.value, state, steps: state.history, durationMs: Date.now() - started }; await this.emit('workflow.completed', runId, { output: state.value, steps: state.history.length, durationMs: result.durationMs }); return result;
    } catch (error) { await this.emit('workflow.failed', runId, { error: error instanceof Error ? error.message : String(error), steps: state.history.length }); throw error; }
  }
  private startNode(): WorkflowNode { if (this.startId) return this.nodes.get(this.startId)!; const incoming = new Set(this.edges.map((edge) => edge.to)); const node = [...this.nodes.values()].find((candidate) => !incoming.has(candidate.id)); if (!node) throw new Error('Workflow graph has no start node'); return node; }
  private selectEdge(edges: WorkflowEdge[], value: unknown): WorkflowEdge | undefined { if (edges.length <= 1) return edges[0]; const label = typeof value === 'boolean' ? String(value) : typeof value === 'string' ? value : undefined; return edges.find((edge) => edge.label === label) ?? edges.find((edge) => !edge.label) ?? edges[0]; }
  private async executeNode(node: WorkflowNode, state: WorkflowState, runId: string, options: WorkflowRunOptions): Promise<WorkflowStep> { const started = new Date().toISOString(); let attempts = 0; let output: unknown; let lastError: unknown; const retries = node.retries ?? 0; await this.emit('workflow.node.started', runId, { nodeId: node.id, type: node.type }); while (attempts <= retries) { attempts += 1; try { output = await withTimeout(Promise.resolve(node.run(state, { runId, signal: state.signal, events: this.events })), options.timeoutMs, state.signal); const step = { nodeId: node.id, type: node.type, input: state.value, output, startedAt: started, completedAt: new Date().toISOString(), attempts }; await this.emit('workflow.node.completed', runId, { nodeId: node.id, type: node.type, attempts }); return step; } catch (error) { lastError = error; if (attempts > retries) break; } } const error = lastError instanceof Error ? lastError : new Error(String(lastError)); await this.emit('workflow.node.failed', runId, { nodeId: node.id, error: error.message, attempts }); throw error; }
  private async emit(type: import('@agentforge-oss/core').AgentEventType, runId: string, data: Record<string, unknown>) { await this.events.emit({ type, runId, data, timestamp: new Date().toISOString() }); }
}

export class WorkflowBuilder {
  private readonly nodes = new Map<string, WorkflowNode>(); private readonly edges: WorkflowEdge[] = []; private start?: string;
  constructor(private readonly name: string) {}
  add(node: WorkflowNode): this { if (this.nodes.has(node.id)) throw new Error(`Duplicate workflow node: ${node.id}`); this.nodes.set(node.id, node); return this; }
  connect(from: string, to: string, options: Omit<WorkflowEdge, 'from' | 'to'> = {}): this { this.edges.push({ from, to, ...options }); return this; }
  setStart(id: string): this { this.start = id; return this; }
  build(): Workflow { return new Workflow({ name: this.name, nodes: [...this.nodes.values()], edges: this.edges, start: this.start }); }
}

async function withTimeout<T>(promise: Promise<T>, timeoutMs: number | undefined, signal: AbortSignal): Promise<T> { if (!timeoutMs) return promise; return new Promise((resolve, reject) => { let timer = setTimeout(() => reject(new AgentForgeError(`Workflow node timed out after ${timeoutMs}ms`, 'TIMEOUT')), timeoutMs); const abort = () => { clearTimeout(timer); reject(new CancellationError()); }; if (signal.aborted) abort(); signal.addEventListener('abort', abort, { once: true }); promise.then((value) => { clearTimeout(timer); signal.removeEventListener('abort', abort); resolve(value); }, (error) => { clearTimeout(timer); signal.removeEventListener('abort', abort); reject(error); }); }); }
