import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { basename, dirname, join, resolve } from 'node:path';

const files: Record<string, string> = {
  'package.json': `{
  "name": "{{name}}",
  "private": true,
  "packageManager": "pnpm@9.15.5",
  "type": "module",
  "scripts": { "run": "agentforge run src/agent.ts", "chat": "agentforge chat src/agent.ts", "start": "agentforge" },
  "dependencies": { "@agentforge/core": "^0.1.0", "@agentforge/cli": "^0.1.0", "@agentforge/models": "^0.1.0" },
  "devDependencies": { "tsx": "^4.19.2", "typescript": "^5.7.2" }
}
`,
  'agentforge.config.ts': `import type { AgentForgeConfig } from '@agentforge/cli';

const config: AgentForgeConfig = {
  name: '{{name}}',
  entry: 'src/agent.ts',
  providers: [
    { name: 'mock', description: 'Offline deterministic provider' },
    { name: 'custom-provider-module', description: 'Set AGENTFORGE_PROVIDER_MODULE to any ModelProvider package or file URL' },
  ],
  tools: [],
  workflows: [],
};

export default config;
`,
  'src/agent.ts': `import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { Agent, type ModelProvider, type ModelResponse } from '@agentforge/core';

const mockModel: ModelProvider = {
  provider: 'mock',
  model: 'agentforge-local',
  async generate(request): Promise<ModelResponse> {
    const input = request.messages.at(-1)?.content ?? '';
    return { id: 'mock-response', content: 'AgentForge received: ' + input, finishReason: 'stop', model: 'agentforge-local', usage: { inputTokens: input.length, outputTokens: input.length, totalTokens: input.length * 2 } };
  },
};

async function loadModel(): Promise<ModelProvider> {
  const moduleName = process.env.AGENTFORGE_PROVIDER_MODULE;
  if (!moduleName) return mockModel;
  const specifier = moduleName.startsWith('.') || moduleName.startsWith('/') ? pathToFileURL(resolve(process.cwd(), moduleName)).href : moduleName;
  const loaded = await import(specifier) as Record<string, unknown>;
  const options = { provider: process.env.AGENTFORGE_PROVIDER ?? 'custom', model: process.env.AGENTFORGE_MODEL, baseUrl: process.env.AGENTFORGE_BASE_URL };
  const factory = typeof loaded.createProvider === 'function' ? loaded.createProvider : typeof loaded.createModel === 'function' ? loaded.createModel : undefined;
  const candidate = factory ? await (factory as (options: typeof options) => unknown)(options) : loaded.model ?? loaded.default;
  if (!candidate || typeof candidate !== 'object' || typeof (candidate as { generate?: unknown }).generate !== 'function') throw new Error('Custom provider must export a ModelProvider as default/model, createProvider(options), or createModel(options).');
  return candidate as ModelProvider;
}

export async function run(input = 'Hello from AgentForge'): Promise<unknown> {
  const model = await loadModel();
  return new Agent({ name: '{{name}}', model, instructions: 'Be concise and factual.' }).run(input);
}
`,
  'provider.example.mjs': `export default {
  provider: 'custom-example',
  model: 'local-custom-v1',
  async generate(request) {
    const input = request.messages.at(-1)?.content ?? '';
    return { id: 'custom-example', content: 'Custom provider: ' + input, finishReason: 'stop', model: 'local-custom-v1', usage: { inputTokens: 0, outputTokens: 0, totalTokens: 0 } };
  },
};
`,
  'tsconfig.json': `{
  "compilerOptions": { "target": "ES2022", "module": "NodeNext", "moduleResolution": "NodeNext", "strict": true, "esModuleInterop": true, "skipLibCheck": true },
  "include": ["src/**/*.ts", "agentforge.config.ts"]
}
`,
  'README.md': `# {{name}}

Generated by AgentForge. Install dependencies, then start an interactive session:

\`\`\`bash
{{install}}
{{start}}
\`\`\`
{{install_note}}
The generated agent uses a deterministic local model so it runs without paid API credentials. Custom providers may export a ModelProvider as \`default\` or \`model\`, or export \`createProvider(options)\` / \`createModel(options)\`. Select one with \`/connect ./provider.mjs\` or \`AGENTFORGE_PROVIDER_MODULE=./provider.mjs\`. Start it with \`{{install}}\` followed by \`{{runner}}\`. For OpenAI, Anthropic, or Gemini, install \`@agentforge/models\`, then replace the model in \`src/agent.ts\` with \`createModel({ provider: 'openai' })\` and set the provider environment variable.
`,
};

function validName(name: string): boolean {
  return /^[a-zA-Z][a-zA-Z0-9._-]{0,63}$/.test(name) && name !== '.' && name !== '..';
}

export async function scaffold(name: string, cwd = process.cwd(), force = false, localRoot?: string): Promise<string> {
  const target = name === '.' ? resolve(cwd) : resolve(cwd, name);
  const projectName = name === '.' ? basename(target) : name;
  if (!validName(projectName)) throw new Error('Project name must start with a letter and contain only letters, numbers, dots, underscores, or hyphens.');
  const install = localRoot ? 'pnpm install' : 'npm install';
  const runner = localRoot ? 'pnpm exec agentforge' : 'npx agentforge';
  const installNote = localRoot
    ? `\n> Local-link mode: \`@agentforge/core\` and \`@agentforge/cli\` are linked from ${resolve(localRoot)} via \`file:\` dependencies. Run \`pnpm build\` in that repository after changing framework code. Packages are not published yet; this project will not install from a registry.\n`
    : '';
  const replacements: Array<[string, string]> = [
    ['{{name}}', projectName],
    ['{{install}}', install],
    ['{{runner}}', runner],
    ['{{start}}', `${runner} chat`],
    ['{{install_note}}', installNote],
  ];
  await mkdir(target, { recursive: true });
  for (const [relative, template] of Object.entries(files)) {
    const path = join(target, relative);
    await mkdir(dirname(path), { recursive: true });
    const content = replacements.reduce((text, [placeholder, value]) => text.replaceAll(placeholder, value), template);
    if (!force) {
      try { await writeFile(path, '', { flag: 'wx' }); } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== 'EEXIST') throw error;
        throw new Error(`Refusing to overwrite ${path}; use --force only for a scaffold you control.`);
      }
      await writeFile(path, content);
    } else {
      await writeFile(path, content);
    }
  }
  if (localRoot) {
    const packagePath = join(target, 'package.json');
    const packageJson = JSON.parse(await readFile(packagePath, 'utf8')) as { dependencies?: Record<string, string> };
    packageJson.dependencies = { ...(packageJson.dependencies ?? {}) };
    for (const packageName of ['core', 'cli']) packageJson.dependencies[`@agentforge/${packageName}`] = `file:${resolve(localRoot, 'packages', packageName)}`;
    delete packageJson.dependencies['@agentforge/models'];
    await writeFile(packagePath, `${JSON.stringify(packageJson, null, 2)}\n`);
  }
  return target;
}
