export type MemoryType = 'conversation' | 'working' | 'long-term';
export interface Memory { id: string; namespace: string; type: MemoryType; content: string; metadata: Record<string, unknown>; createdAt: Date; expiresAt?: Date; score?: number; }
export interface RememberInput { id?: string; namespace: string; type?: MemoryType; content: string; metadata?: Record<string, unknown>; expiresAt?: Date; }
export interface RecallQuery { namespace: string; query?: string; type?: MemoryType; limit?: number; after?: Date; metadata?: Record<string, unknown>; }
export interface MemoryProvider { remember(input: RememberInput): Promise<Memory>; recall(query: RecallQuery): Promise<Memory[]>; forget(id: string, namespace?: string): Promise<boolean>; clear(namespace: string): Promise<number>; }

const memoryId = () => `mem_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 10)}`;
const matchesMetadata = (memory: Memory, expected?: Record<string, unknown>) => !expected || Object.entries(expected).every(([key, value]) => memory.metadata[key] === value);
const score = (content: string, query?: string) => { if (!query) return 1; const words = new Set(query.toLowerCase().split(/\W+/).filter(Boolean)); if (!words.size) return 1; const contentWords = new Set(content.toLowerCase().split(/\W+/).filter(Boolean)); return [...words].filter((word) => contentWords.has(word)).length / words.size; };

export class InMemoryMemoryProvider implements MemoryProvider {
  private readonly records = new Map<string, Memory>();
  async remember(input: RememberInput): Promise<Memory> { const memory: Memory = { id: input.id ?? memoryId(), namespace: input.namespace, type: input.type ?? 'conversation', content: input.content, metadata: input.metadata ?? {}, createdAt: new Date(), expiresAt: input.expiresAt }; this.records.set(memory.id, memory); return memory; }
  async recall(query: RecallQuery): Promise<Memory[]> { const now = Date.now(); return [...this.records.values()].filter((memory) => memory.namespace === query.namespace && (!query.type || memory.type === query.type) && (!query.after || memory.createdAt >= query.after) && (!memory.expiresAt || memory.expiresAt.getTime() > now) && matchesMetadata(memory, query.metadata)).map((memory) => ({ ...memory, score: score(memory.content, query.query) })).filter((memory) => !query.query || (memory.score ?? 0) > 0).sort((a, b) => (b.score ?? 0) - (a.score ?? 0) || b.createdAt.getTime() - a.createdAt.getTime()).slice(0, query.limit ?? 20); }
  async forget(id: string, namespace?: string): Promise<boolean> { const memory = this.records.get(id); if (!memory || (namespace && memory.namespace !== namespace)) return false; return this.records.delete(id); }
  async clear(namespace: string): Promise<number> { let count = 0; for (const [id, memory] of this.records) if (memory.namespace === namespace) { this.records.delete(id); count += 1; } return count; }
}

export interface QueryResult<T = Record<string, unknown>> { rows: T[]; rowCount?: number | null; }
export interface PostgresClient { query<T = Record<string, unknown>>(text: string, values?: unknown[]): Promise<QueryResult<T>>; }
interface MemoryRow { id: string; namespace: string; type: MemoryType; content: string; metadata: Record<string, unknown>; created_at: string | Date; expires_at: string | Date | null; score?: number; }
const fromRow = (row: MemoryRow): Memory => ({ id: row.id, namespace: row.namespace, type: row.type, content: row.content, metadata: row.metadata ?? {}, createdAt: new Date(row.created_at), expiresAt: row.expires_at ? new Date(row.expires_at) : undefined, score: row.score });

export class PostgresMemoryProvider implements MemoryProvider {
  constructor(private readonly client: PostgresClient, private readonly table = 'agentforge_memories') { if (!/^[a-z_][a-z0-9_]*$/i.test(table)) throw new Error('Invalid memory table name'); }
  async migrate(): Promise<void> { await this.client.query(`CREATE TABLE IF NOT EXISTS ${this.table} (id text PRIMARY KEY, namespace text NOT NULL, type text NOT NULL, content text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz); CREATE INDEX IF NOT EXISTS ${this.table}_namespace_idx ON ${this.table}(namespace, type, created_at DESC)`); }
  async remember(input: RememberInput): Promise<Memory> { const id = input.id ?? memoryId(); const result = await this.client.query<MemoryRow>(`INSERT INTO ${this.table} (id, namespace, type, content, metadata, expires_at) VALUES ($1,$2,$3,$4,$5::jsonb,$6) ON CONFLICT (id) DO UPDATE SET namespace=EXCLUDED.namespace,type=EXCLUDED.type,content=EXCLUDED.content,metadata=EXCLUDED.metadata,expires_at=EXCLUDED.expires_at RETURNING *`, [id, input.namespace, input.type ?? 'conversation', input.content, JSON.stringify(input.metadata ?? {}), input.expiresAt ?? null]); const row = result.rows[0]; if (!row) throw new Error('PostgreSQL did not return stored memory'); return fromRow(row); }
  async recall(query: RecallQuery): Promise<Memory[]> { const values: unknown[] = [query.namespace]; const clauses = ['namespace = $1', '(expires_at IS NULL OR expires_at > now())']; if (query.type) { values.push(query.type); clauses.push(`type = $${values.length}`); } if (query.after) { values.push(query.after); clauses.push(`created_at >= $${values.length}`); } if (query.metadata) { values.push(JSON.stringify(query.metadata)); clauses.push(`metadata @> $${values.length}::jsonb`); } if (query.query) { values.push(query.query); clauses.push(`to_tsvector('simple', content) @@ plainto_tsquery('simple', $${values.length})`); } values.push(query.limit ?? 20); const rank = query.query ? `ts_rank(to_tsvector('simple', content), plainto_tsquery('simple', $${values.length - 1})) AS score` : '1::real AS score'; const result = await this.client.query<MemoryRow>(`SELECT *, ${rank} FROM ${this.table} WHERE ${clauses.join(' AND ')} ORDER BY score DESC, created_at DESC LIMIT $${values.length}`, values); return result.rows.map(fromRow); }
  async forget(id: string, namespace?: string): Promise<boolean> { const result = await this.client.query(`DELETE FROM ${this.table} WHERE id=$1${namespace ? ' AND namespace=$2' : ''}`, namespace ? [id, namespace] : [id]); return (result.rowCount ?? 0) > 0; }
  async clear(namespace: string): Promise<number> { const result = await this.client.query(`DELETE FROM ${this.table} WHERE namespace=$1`, [namespace]); return result.rowCount ?? 0; }
}
